### ISSUE TITLE
Issue with system messages

### ISSUE THREAD

**Issue by basinbasin** [ainslec/adventuron-issue-tracker#366] opened 2021-03-22 17:16 UTC
68j

Porting over an old Quilled game where the object descriptions include full stops, e.g.

a credit.

I overwrite the standard "You see" header, and remove the additional full stops added at the end of any objects listed by adding the following system messages into the relevant theme:

object_list_end_text = ""
object_list_header		=<Jack also noticed:<14>>

In game, the additional full stop is removed, but "You see" is still displayed, before any objects, rather than "Jack also noticed:".

Also, there is logic in game to swap themes at certain points. (The subfont subroutines mentioned below just execute a set_themes command.)

	: match "x cred" {
 :if(is_present "obj68") {

	: gosub "subfont3";
	: pause "50";
	: clear_screen;
	: print {(mess162)};
	: pause "50";
	: press_any_key;
	: gosub "subfont2";
	: redescribe;
		}
	}

After the above logic is called, the object_list_end_text override is ignored, and the credit is displayed with two full stops:

You see a credit..

**Comment by ainslec** [comment] 2021-03-22 17:24
I can't compile your code snippet therefore it's hard for me to solve the
issue, or to confirm I solved it.

If you could do me a huge favour, and when raising issues, please provide
concise standalone code to demonstrate the issue (a fully compliable piece
of adventuron - self contained) . If you can do this, I can certainly take
a look at the issue.

Then also say what you have to type to trigger the issue, what you expected
to happen (expected), and what actually happens (actual). I have several
hundred open issues so without well formed bug reports it takes too long to
try to narrow down the error, especially as I don't understand.

Chris

**Comment by basinbasin** [comment] 2021-03-24 10:12
Sorry. Lemme try again with this then...

```
start_at = first

start_theme  = theme1


locations { 

first : location  "First location." ;

}

objects {

	credit :  object "a credit." start_at= "first";

}


themes {
   
   theme1 :theme {
      
     theme_settings {
        layout = H G D O
        columns = 40
     
      }
      
      colors { 
         paper                       = 1
         pen = 6
         border                      = 0
      }

	system_messages {
	
	   object_list_final_separator = ""
      object_list_end_text = ""
		object_list_header		=<Jack also noticed:<14>>
		on_get  = <Jack picked up  <12>> ${entity}

} 
   }
   
   
   

theme3 :theme {

 theme_settings {
      columns = 40
       }
     
      
      colors { 
         paper                       = 2
         pen                   = 7
         border                      = 0
      }
      
   }

}


on_command {

: match "x credit" {
   :if(is_present "credit") {
   : gosub "subfont3";
   : pause "50";
   : clear_screen;
   : print "The credit is unremarkable.";
   : pause "50";
   : press_any_key;
   : gosub "subfont1";
   : redescribe;
	}
}


}

subroutines {
            

subfont1 : subroutine {
   
   : set_theme "theme1" ; 
  
}

subfont3 : subroutine {
   
   : set_theme "theme3" ;
} 

}

```
Issues:

**EXPECTED: Start the game, and "Jack also noticed a credit" is expected, because the on_get system message has been overridden. Note there's only one full stop at the end of credit, so object_list_final_separator = "" object_list_end_text = ""  must be working?** 

First location.

You see a credit.

>EXAMINE CREDIT

The credit is unremarkable.

**EXPECTED: Examining the credit sets a new theme to display the above message, and then calls the original theme again. I still expect to see "Jack also noticed a credit", but see actual below, and this time the  object_list_final_separator = ""
      object_list_end_text = "" entries are now being ignored and an additional full stop added at the end of credit.**

First location.

You see a credit..

>GET CREDIT

You take the credit..

**EXPECTED: As before, on_get has been overridden, so we should see "Jack picked up the credit." Now let's restart the game.**

>QUIT

QUESTION -> Would you like to forfeit the game?

Would you like to forfeit the game?

>?Y

ANSWER -> yes

You have quit the game.
<< START >>

Click to continue ...

First location.

**EXPECTED: Start the game, and "Jack also noticed a credit" is expected. Actual is per the transcript below**

You see a credit.

>GET CREDIT

Jack picked up   the credit.

**EXPECTED: As above. so the system message override has worked in this instance. But in the above example game, the success of this and other system message overrides seems intermittent.**

**Comment by ainslec** [comment] 2021-03-24 12:05
Seems to be a configuration issue, not a bug.

It appears you were setting the system property for non verbose object lists, when Adventuron defaults to verbose object lists by default.

If you want your objects listed in a concise way, then use the "single_line" lister type (demonstrated below). If you want your objects listed in a verbose way (like an English language sentence), then use the "object_list_header" system property instead, and set your list type to "verbose" (which is the default anyway).

The on_get message seems to work for me in this code snippet below.

Let me know if you have any follow up queries, or if this works for you.

```
start_theme = theme1
start_at    = first

locations { 
   first : location  "First location." ;
}

objects {
	credit :  object "a credit" start_at= "first";
}

themes {
   
   theme1 : theme {
     theme_settings {
        layout = H G D O
        columns = 40
      }
      colors { 
         paper    = 1
         pen      = 6
         border   = 0
      }
      
      lister_objects {
         list_type = single_line
      }

   	system_messages {
   		object_list_header =<Jack also noticed:<14>>\s 
   		on_get  = <Jack picked up <12>> ${entity}.
      } 
   }

   theme3 :theme {
   
      theme_settings {
         columns = 40
      }
      colors { 
         paper                       = 2
         pen                   = 7
         border                      = 0
      }
   }

}


on_command {

   : match "x credit" {
      :if(is_present "credit") {
      : gosub "subfont3";
      : pause "50";
      : clear_screen;
      : print "The credit is unremarkable.";
      : pause "50";
      : press_any_key;
      : gosub "subfont1";
      : redescribe;
   	}
   }
}

subroutines {
   subfont1 : subroutine {
      : set_theme "theme1" ; 
   }
   subfont3 : subroutine {
      : set_theme "theme3" ;
   } 
}
```

**Comment by ainslec** [comment] 2021-03-24 17:55
Closing this as seems it's misconfiguration, please add a comment if you disagree, and I can reopen.

**Closed as completed by ainslec** 2021-03-24 17:55 UTC
Labels: question

**Comment by basinbasin** [comment] 2021-03-25 11:30
Cheers. Understood about the full stops and config. Using the example code you've supplied above though, I still get the issue where the override object_list_header is ignored after a different theme has been set, and we return to the initial theme containing the override. From the transcript:

```
First location.

Jack also noticed: a credit.

>X CREDIT


The credit is unremarkable.


First location.

You see: a credit. [EXPECTED: Jack also noticed a credit.]

```

**Comment by ainslec** [comment] 2021-03-25 11:33
If you want a theme to inherit from (say for example) theme1 use:

`extends = theme1`

If you don't do this then other themes will need their system messages setting explicitly.

**Comment by basinbasin** [comment] 2021-03-25 12:13
Understood, but the example:

1. Starts the game with theme1 set which contains the "Jack also noticed" override
2. X CREDIT causes theme2 to be set to display the message.
3. **BUT** the X CREDIT logic **THEN** sets theme1 to be active **again**, so we should get the "Jack also noticed" override when we return to the location and the objects are listed.

I deliberately set garish paper colours for the themes so it's nice and obvious which theme is currently active.

**Comment by ainslec** [comment] 2021-03-25 12:28
Theme 1 has a verbose lister, 

The following would never be used.

`object_list_header		=<Jack also noticed <14>>`

In a verbose lister you need to use:

`object_list_header_verbose = <Jack also noticed <14>>`

A verbose lister is a lister in which a full sentence is constructed with the objects. e.g. You see a lamp, a spoon, and a goat. A non verbose lister basically puts a header in front, and comma separates elements without a special value before the last element ("and ") as in the verbose lister.

To change the type of lister your theme wants simple use this.

```
      lister_objects {
         list_type = verbose | list | list_no_article | single_line | single_line_no_article | single_line_no_article_no_adjective
      }
```

All these settings are exposed via CONTROL + SPACE.

I hope this helps.,

**Comment by basinbasin** [comment] 2021-03-25 17:45
One last try with this, I think. :-)

Understood about the config combinations. I've changed the lister to verbose. What I'm still struggling with is that the same location and same object in the same theme is returning different _You see object_ system message responses before vs after the X CREDIT is called. Irrespective of config, or my shoddy coding, if the input is the same, but the output differs, there's an issue isn't there?

If you paste and run the below, what "You see an object"  message is shown to you on screen before compared with after the X CREDIT command?

```


start_theme = theme1
start_at    = first

locations { 
   first : location  "First location." ;
}

objects {
	credit :  object "a credit." start_at= "first"  ;
}

themes {
   
   theme1 : theme {
     theme_settings {
        layout = H G D O
        columns = 40
      }
      colors { 
         paper    = 1
         pen      = 6
         border   = 0
      }
      
      lister_objects {
         list_type = verbose
      }

   	system_messages {
   		object_list_header_verbose = <Verbose version: Jack also noticed - <14>>
   		object_list_header =<Jack also noticed:<14>>\s 
   		on_get  = <Jack picked up <12>> ${entity}.
   	
      } 
   }

   theme3 :theme {
   
      theme_settings {
         columns = 40
      }
      colors { 
         paper       = 2
         pen         = 7
         border      = 0
      }
   }

}


on_command {

   : match "x credit" {
      :if(is_present "credit") {
      : gosub "subfont3";
      : pause "50";
      : clear_screen;
      : print "The credit is unremarkable.";
      : pause "50";
      : press_any_key;
      : gosub "subfont1";
      : redescribe;
     
   	}
   }
}

on_describe {
   : print {("Sysmess 1580: \n\"" + sys(1580) +"\"" )};

}
subroutines {
   subfont1 : subroutine {
      : set_theme "theme1" ; 
   }
   subfont3 : subroutine {
      : set_theme "theme3" ;
   } 
}
```

**Comment by ainslec** [comment] 2021-03-25 18:49
You isolated it ... annnnnnnnd ... it is indeed a bug.

The bug fix will be released in the upcoming beta 70 release.

Chris
