### ISSUE TITLE
bug: "redescribe = auto_beta" doesn't work as intended

### ISSUE THREAD

**Issue by hnejfnvjojgrogjwm** [ainslec/adventuron-issue-tracker#317] opened 2021-03-05 19:18 UTC
Sorry I can not reproduce it in a small piece of code. I have attached the code of my game.
You can see the game working with all the assets here:
http://roboscape.co.uk/Mazmorras%20de%20Antur/index_english.html
Please let me know if you need anything else.
[Mazmorras_de_Antur_EN_20210305_1904.txt](https://github.com/ainslec/adventuron-issue-tracker/files/6092864/Mazmorras_de_Antur_EN_20210305_1904.txt)

**Comment by ainslec** [comment] 2021-03-06 19:19
Can you tell me what is happening that you don't expect to be happening, and how to reproduce the error?

**Comment by hnejfnvjojgrogjwm** [comment] 2021-03-06 20:32
This is the bug you asked me to report. The game is reproducing constant press_any_key situations and flickering screen. I am not sure how that "redescribe = auto_beta" is supposed to work.

**Comment by ainslec** [comment] 2021-03-20 00:57
Looks like having dynamic graphics makes the auto redescribe procedure be over sensitive.

```
// If typing EXAMINE SPIDER, then a PRESS ANY KEY event is created after the message is displayed.
// But if commenting out the graphics block, no PRESS ANY KEY will be added (which is correct as the room state did not change)

start_at = loc_pasillo01
redescribe = auto_beta

locations {
   loc_pasillo01 : location "You are at a crossroads, barely lit by a TORCH on the wall." header="Fork" {
      on_describe{
      :if(is_present"char_spider"){
         :print"The huge spider guards its web in the middle of the threshold, blocking the way.";}
      }
   }
}

objects {
   char_spider:scenery "a giant spider" start_at="loc_pasillo01";
}

on_command{
   :if_examine "char_spider"{
      :print"Eight legs that move nervously around a fat and hairy body. She looks at you with her six bright red eyes. You are not going to sleep tonight, and you know it.";
   }
}

assets {
   graphics {
      loc_pasillo01_a: jpeg "graphics/loc_pasillo01_a.jpg";
      loc_pasillo01_b: jpeg "graphics/loc_pasillo01_b.jpg";
      loc_pasillo01:dynamic_graphic {( is_present"char_spider" ? "loc_pasillo01_a" : "loc_pasillo01_b" )}
   }
}
```

**Comment by ainslec** [comment] 2021-03-21 01:17
Fixed in beta 70.

**Closed as completed by ainslec** 2021-03-21 01:17 UTC
Labels: priority
