### ISSUE TITLE
[BUG]  Printing a numeric variable in global on_describe causes problems.

### ISSUE THREAD

**Issue by nww02** [ainslec/adventuron-issue-tracker#335] opened 2021-03-11 02:06 UTC
I'm attempting to print an integer value in the global on_describe() function.     Adventuron hangs attempting to do it.     If I print static text, it's fine.

![image](https://user-images.githubusercontent.com/46803513/110724548-e4381b00-820d-11eb-812f-24c2066730b5.png)

As can be seen, the main room text appears, and the LINE1 appears, and then the parser breaks.
![image](https://user-images.githubusercontent.com/46803513/110724653-1b0e3100-820e-11eb-8204-26735874e2df.png)

it does this on both static and dynamic integers...

**Comment by ainslec** [comment] 2021-03-11 12:52
Related to issue #297

**Comment by ainslec** [comment] 2021-03-15 14:04
Closing this as duplicate of #297 .

**Closed as completed by ainslec** 2021-03-15 14:04 UTC
