### ISSUE TITLE
Absence of white space causes an error in connections

### ISSUE THREAD

**Issue by warrigal24** [ainslec/adventuron-issue-tracker#252] opened 2021-01-08 01:40 UTC
Consider the following definition in the `connections{}` section:
```
connections {
   from, direction, to = [room01, south, room02]
}
```
This causes an error saying, '`Multiple headers not permitted for attr = [ a, b, c ] syntax.`' I have no idea what this error means.

Now consider the following definition:
```
connections {
   from, direction, to = [
   room01, south, room02]
}
```
This causes an error saying, '`Encountered unexpected token: "]" "]"`' I can't see anything wrong with that token or that syntax.

Now consider the following definition:
```
connections {
   from, direction, to = [room01, south, room02
   ]
}
```
This causes an error saying, '`Encountered unexpected token: "\n" <EOL>`' Huh?

Finally, consider the following definition:
```
connections {
   from, direction, to = [
   room01, south, room02
   ]
}
```
This does not cause an error. So, the only difference in all these definitions is the presence of white space (spaces, tabs and new lines). This is wrong. The absence of white space should not make any difference in this scenario.

**Comment by ainslec** [comment] 2021-03-15 14:02
Closing this.

This is by design in the Rion object notation syntax(used in Adventuron). It forces each line to have the 3 elements on at a time. Were this not imposed then you might be able to define 6 elements or 7 elements on a line, and whilst the computer could read it, no-one else could. The only real use for this is if you want to compress the text down if there is one set of 3 elements, and that's too much of an edge case to change the design.

**Closed as completed by ainslec** 2021-03-15 14:02 UTC
Labels: Rion, LowPriority
