### ISSUE TITLE
[BUG / CONFIG?]  "r -" and "l -" both map to whichever is the first match.

### ISSUE THREAD

**Issue by nww02** [ainslec/adventuron-issue-tracker#457] opened 2021-06-30 15:38 UTC
If you attempt to watch for the commands "r" and "l", then they seem to be aliases out of the box, so both will cause whichever is listed first to fire.

Is there a way to "de-alias" them? Should it be like this, or is it a bug?
```
start_at = my_location

locations {
   my_location : location "You are in a room." ;
}

on_command {
   :match "r -" {
      :print "You typed 'r'";
      :done;
   }

   :match "l -" {
      :print "You typed 'l'";
        :done;
   }
}

```

As demonstrated here...

![image](https://user-images.githubusercontent.com/46803513/123990065-5b620c80-d9c1-11eb-9388-e04af53e87ff.png)

Even adding them as separate items in the vocab still has them tied together:-

![image](https://user-images.githubusercontent.com/46803513/123990303-8f3d3200-d9c1-11eb-891a-8f77987fd2e3.png)

**Comment by nww02** [comment] 2021-06-30 15:44
I have a workaround, which is:-

![image](https://user-images.githubusercontent.com/46803513/123991210-6e291100-d9c2-11eb-8102-82b02aae5dd7.png)


this seems to allow it to drop through into the other handler.

**Comment by ainslec** [comment] 2021-07-01 21:11
if (original "verb" == "l") { .... }

**Comment by nww02** [comment] 2021-07-01 22:06
Yeah, that works too.   So it's not a biggie, but might trip someone up if they're trying to implement "right" and "left" as directions :)

**Comment by ainslec** [comment] 2022-03-06 12:35
Closing this as any "solution" would require quite a lot of static analysis, and it's technically a feature not a bug.

**Closed as completed by ainslec** 2022-03-06 12:35 UTC
